name: dialog
on:
  push:
    branches:
    paths-ignore: ["README.md"]
  workflow_dispatch:

jobs:
  turkeyGitops:
    uses: hubs-foundation/hubs-ops/.github/workflows/turkeyGitops.yml@master
    with:
      DOCKER_HUB_USR: ${{ vars.DOCKER_HUB_USR || 'hubsfoundation' }}
      registry: ${{ vars.DOCKER_REGISTRY || 'hubsfoundation' }}
    secrets:
      DOCKER_HUB_PWD: ${{ secrets.DOCKER_HUB_PWD }}
